name: plan

on:
  pull_request:
    paths:
      - "stacks/**"
      - "modules/**"
      - "config/**"
      - "scripts/**"
      - ".github/workflows/**"

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - stack: website
            environment: prod
          - stack: tools
            environment: prod
    uses: ./.github/workflows/_terraform.yml
    with:
      stack: ${{ matrix.stack }}
      environment: ${{ matrix.environment }}
      action: plan
